<?php

namespace AppBundle\Repository;

/**
 * TutoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TutoRepository extends \Doctrine\ORM\EntityRepository
{
}
